service: kms-signer
provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - kms:GetPublicKey
        - kms:ListKeyPolicies
        - kms:ListKeys
        - kms:ListResourceTags
        - kms:Sign
        - kms:Verify
      Resource: "arn:aws:kms:<REGION>:<ACCOUNT>:key/<KEY-ID>"
  tracing:
    lambda: true

package:
  artifact: target/kms-signer-dev.jar

functions:
  sign:
    handler: com.soroush.SigningHandler
    events:
      - http:
          path: sign
          method: post
